version: '3.8'

services:
  mysql:
    image: mysql:8.0 
    container_name: znap-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pedidos_service
      MYSQL_USER: znap_user
      MYSQL_PASSWORD: znap_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local