CREATE TABLE pedidos (
    id VARCHAR(36) PRIMARY KEY,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_cliente VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id)
);